name: join
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: pre-join
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: joined
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
