name: json-replay
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue:
    required: true
  - name: file
    inputType: FreeText
    description: Name of the file to ingest.
    defaultValue:
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
