name: user_activity_events_source
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: user_activity
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
