name: user_purchases_events_source
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: user_purchases
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
